INSERT INTO ACCOUNT_USER(ID, NAME, CREATED_AT, UPDATED_AT)
VALUES (1, '홍길동', now(), now());
INSERT INTO ACCOUNT_USER(ID, NAME, CREATED_AT, UPDATED_AT)
VALUES (2, '권신범', now(), now());
INSERT INTO ACCOUNT_USER(ID, NAME, CREATED_AT, UPDATED_AT)
VALUES (3, '권하정', now(), now());

